/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PERIPHERALS_H_
#define _PERIPHERALS_H_

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "fsl_common.h"
#include "fsl_lpit.h"
#include "fsl_lpuart.h"
#include "fsl_clock.h"

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/
/* Definitions for BOARD_InitPeripherals functional group */
/* BOARD_InitPeripherals defines for LPIT0 */
/* Definition of peripheral ID. */
#define LPIT0_PERIPHERAL LPIT0
/* Definition of clock source frequency. */
#define LPIT0_CLK_FREQ 96000000UL
/* Definition of ticks count for channel Channel_0. */
#define LPIT0_CHANNEL_0_TICKS 95999999U
/* Definition of channel kLPIT_Chnl_0 ID */
#define LPIT0_CHANNEL_0 kLPIT_Chnl_0
/* LPIT0 interrupt vector ID (number). */
#define LPIT0_IRQN LPIT0_IRQn
/* LPIT0 interrupt handler identifier. */
#define LPIT0_IRQHANDLER LPIT0_IRQHandler
/* Definition of peripheral ID */
#define LPUART0_PERIPHERAL LPUART0
/* Definition of the clock source frequency */
#define LPUART0_CLOCK_SOURCE 10666666UL

/***********************************************************************************************************************
 * Global variables
 **********************************************************************************************************************/
extern const lpit_config_t LPIT0_config;
extern const lpit_chnl_params_t LPIT0_Channel_0_struct;
extern const lpuart_config_t LPUART0_config;

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/

void BOARD_InitPeripherals(void);

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void);

#if defined(__cplusplus)
}
#endif

#endif /* _PERIPHERALS_H_ */
